// *** REQUEST ***
export const REQUEST_UPDATE = "REQUEST_UPDATE";
export const REQUEST_RESET = "REQUEST_RESET";

// *** TRANSACTION ***
export const TRANSACTION_UPDATE = "TRANSACTION_UPDATE";
export const TRANSACTION_RESET = "TRANSACTION_RESET";